const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        UserRegister: {
            firstname: "John",
            lastname: "Doe",
            username: "JohnDoe90",
            email: "john.doe@example.com",
            password: "abcd1234",
            address: "Main Street 10",
            telephone: "12345678"
        },
        UserLogin: {
            emailOrUsername: "admin",
            password: "P@ssword2023"
        },
        PostProduct: {
            $name: "iPhone 2030 Model",
            $imgurl: "example-url.png",
            $description: "Do all on your phone",
            $price: 11999,
            $quantity: 40,
            $brandId: 1,
            $categoryId: 1,
        },
        UpdateProduct: {
            name: "newiPhoneName",
            description: "This iPhone have a new name and price",
            price: 9999
        },
        PostBrand: {
            name: "New brand"
        },
        Updatebrand: {
            name: "Updated brandName"
        },
        PostCategory: {
            name: "New category"
        },
        UpdateCategory: {
            name: "Updated category"
        },
        PostCartitem: {
            quantity: 10
        },
        UpdateCartitem: {
            quantity: 15
        },
        UpdateOrderStatus: {
            statusName: "Completed"
        },
        UpdateUser: {
            address: "Second Street 30",
            telephone: "90909090"
        }
        
        
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})